application:
  name: simple-example-node
  organization: QoveryCommunity
  project: getting-started
  publicly_accessible: true
  ram: 256MB
routers:
- name: main
  custom_domains:
    - branch: master
      domain: abcd.qvy.io
  routes:
  - application_name: simple-example-node
    paths:
    - /

